---
title: "CIND820"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
##Packages

#install.packages('tidyverse')
#install.packages('dplyr')
#install.packages('car')
#install.packages("DescTools")
#install.packages("arules")
#install.packages("Rtools")
#install.packages("stats")
#install.packages("forecast")
#install.packages("TSstudio")
library(arules)
library(DescTools)
library(dplyr)
library(tidyr)
library(car)
library(stats)
library(lubridate)
library(ggplot2)
library(forecast)
library(tseries)
library(caret)
library(TSstudio)
```

```{r read}
cancer_incidence<- read.csv(file="C:/Users/olivi/OneDrive/Documents/DataSets/13100109-eng/13100109.csv", sep = ",")
```

```{r configure}
#first remove columns from cancer incidence frame
##############################################################
cancer_table<- subset(cancer_incidence, select = -c(DGUID,UOM_ID,UOM,SCALAR_FACTOR,SCALAR_ID, VECTOR, COORDINATE, STATUS, SYMBOL, TERMINATED, DECIMALS))

#now remove all rows that contain the characteristic value that we don't want to measure

cancer_cl<-cancer_table[-grep("Statistically different from", cancer_table$Characteristics),]
cancer_cl<- cancer_cl[grep("age-standardized", cancer_cl$Characteristics),]
cancer_cl<-cancer_cl[-grep("95%", cancer_cl$Characteristics),]
#cancer_cl<-cancer_cl[grep("Both", cancer_cl$Sex),]
#cancer_cl<-cancer_cl[grep("All invasive", cancer_cl$Selected.sites.of.cancer..ICD.O.3.),]


#try spread
#remove duplicated elements so spread works
cancer_w<-cancer_cl[!duplicated(cancer_cl),]
cancer_w4<-spread(cancer_w, Characteristics, VALUE)
cancer_w4<- cancer_w4[-grep("Canada", cancer_w4$GEO),]
cancer_w4<- cancer_w4[-grep("Peer", cancer_w4$GEO),]

```

```{r preliminary}
n_distinct(cancer_cl$GEO)
##154

summary(cancer_w4)
str(cancer_w4)

hist(cancer_w4$`Cancer incidence (age-standardized rate per 100,000 population)`)


```

```{r more variables but less obs}
cancer_2<-cancer_table[-grep("Statistically different from", cancer_table$Characteristics),]
cancer_2<-cancer_2[-grep("95%", cancer_2$Characteristics),]
cancer_2<-cancer_2[grep("age-standardized", cancer_2$Characteristics),]
cancer_2<-cancer_2[-grep("Canada", cancer_2$GEO),]
cancer_2<-cancer_2[-grep("Peer", cancer_2$GEO),]
cancer_2<- cancer_2[!duplicated(cancer_2),]


cancer_2.1<- spread(cancer_2, Characteristics, VALUE)

cancer_2.2<- cancer_2.1[,1:5]
cancer_2.2<- spread(cancer_2.2, Selected.sites.of.cancer..ICD.O.3., 'Cancer incidence (age-standardized rate per 100,000 population)')


cancer_2.2<-as.data.frame(unclass(cancer_2.2), stringsAsFactors = TRUE)
#levels(cancer_2.2$GEO)

```

```{r histograms}
hist(cancer_2.2[,4], breaks = 50, main = "All cancer sites")
hist(cancer_2.2[,5], breaks = 50, main = "Bronchus and lung cancer")
hist(cancer_2.2[,6], breaks = 50, main = "Colon cancer")
hist(cancer_2.2[,7], breaks = 50, main = "Female breast cancer")
hist(cancer_2.2[,8], breaks = 25, main = "Prostate cancer")
```

```{r incidence quantiles}

cancer_2.3<- cancer_2.2[,1:3]

cancer_2.3["Quantile_All"]<- CutQ(cancer_2.2[,4], breaks = 6, na.rm=FALSE)
cancer_2.3["Quantile_bronc"]<- CutQ(cancer_2.2[,5], breaks = 6, na.rm=FALSE)
cancer_2.3["Quantile_colon"]<- CutQ(cancer_2.2[,6], breaks = 6, na.rm=FALSE)
cancer_2.3["Quantile_breast"]<- CutQ(cancer_2.2[,7],breaks = 6, na.rm=FALSE)
cancer_2.3["Quantile_prost"]<- CutQ(cancer_2.2[,8], breaks = 6, na.rm =FALSE)
```

```{r EDA}
##not sure if apriori would work with this data, haven't figured it out yet
#when I had results none were pertaining to geography

geo<- list(cancer_2.3$GEO)

#assco_rules<- apriori(cancer_2.3, parameter = list(supp = 0.01, conf = 0.05), appearance = list(lhs=geo))
#summary(assco_rules)
#inspect(assco_rules)
```

```{r GEO split}
#######SPLIT NEW TABLE INTO GEOGRAPHIC REGIONS
##with quantiles
cancer_ON.3<- cancer_2.3[grep("Ontario", cancer_2.3$GEO),]

cancer_QC.3<- cancer_2.3[grep("Quebec", cancer_2.3$GEO),]
cancer_BC.3<- cancer_2.3[grep("British Columbia", cancer_2.3$GEO),]

cancer_MB.3<- cancer_2.3[grep("Manitoba", cancer_2.3$GEO),]
cancer_SK.3<- cancer_2.3[grep("Saskatchewan", cancer_2.3$GEO),]
cancer_AB.3<- cancer_2.3[grep("Alberta", cancer_2.3$GEO),]
cancer_midwest.3<- rbind(cancer_MB.3,cancer_AB.3,cancer_SK.3)

cancer_NL.3<- cancer_2.3[grep("Newfoundland", cancer_2.3$GEO),]
cancer_NB.3<- cancer_2.3[grep("New Brunswick", cancer_2.3$GEO),]
cancer_NS.3<- cancer_2.3[grep("Nova Scotia", cancer_2.3$GEO),]
cancer_PEI.3<- cancer_2.3[grep("Prince Edward Island",cancer_2.3$GEO),]
cancer_maritimes.3<- rbind(cancer_NS.3,cancer_NB.3,cancer_NL.3,cancer_PEI.3)

cancer_YT.3<- cancer_2.3[grep("Yukon", cancer_2.3$GEO),]
cancer_NWT.3<-cancer_2.3[grep("Northwest Territories", cancer_2.3$GEO),]
cancer_NVT.3<-cancer_2.3[grep("Nunavut", cancer_2.3$GEO),]
cancer_territories.3<- rbind(cancer_NWT.3,cancer_YT.3,cancer_NVT.3)


##continuous
cancer_ON.2<- cancer_2.2[grep("Ontario", cancer_2.2$GEO),]
cancer_QC.2<- cancer_2.2[grep("Quebec", cancer_2.2$GEO),]
cancer_BC.2<- cancer_2.2[grep("British Columbia", cancer_2.2$GEO),]

cancer_MB.2<- cancer_2.2[grep("Manitoba", cancer_2.2$GEO),]
cancer_SK.2<- cancer_2.2[grep("Saskatchewan", cancer_2.2$GEO),]
cancer_AB.2<- cancer_2.2[grep("Alberta", cancer_2.2$GEO),]
cancer_midwest.2<- rbind(cancer_MB.2,cancer_AB.2,cancer_SK.2)

cancer_NL.2<- cancer_2.2[grep("Newfoundland", cancer_2.2$GEO),]
cancer_NB.2<- cancer_2.2[grep("New Brunswick", cancer_2.2$GEO),]
cancer_NS.2<- cancer_2.2[grep("Nova Scotia", cancer_2.2$GEO),]
cancer_PEI.2<- cancer_2.2[grep("Prince Edward Island",cancer_2.2$GEO),]
cancer_maritimes.2<- rbind(cancer_NS.2,cancer_NB.2,cancer_NL.2,cancer_PEI.2)

cancer_YT.2<- cancer_2.2[grep("Yukon", cancer_2.2$GEO),]
cancer_NWT.2<-cancer_2.2[grep("Northwest Territories", cancer_2.2$GEO),]
cancer_NVT.2<-cancer_2.2[grep("Nunavut", cancer_2.2$GEO),]
cancer_territories.2<- rbind(cancer_NWT.2,cancer_YT.2,cancer_NVT.2)


```

```{r preliminary time series analysis.1}
##try time series analysis
###Just a peek

ts_ON.2<-ts(data = cancer_ON.2, frequency = n_distinct(cancer_ON.2$GEO) ,start = 2001, end = 2015)
ts.plot(ts_ON.2)

ts_QC.2<-ts(data = cancer_QC.2, frequency = n_distinct(cancer_QC.2$GEO) ,start = 2001, end = 2015)
ts.plot(ts_QC.2)

ts_BC.2<-ts(data = cancer_BC.2, frequency = n_distinct(cancer_BC.2$GEO) ,start = 2001, end = 2015)
ts.plot(ts_BC.2)

ts_midwest.2<-ts(data = cancer_midwest.2, frequency = n_distinct(cancer_midwest.2$GEO) ,start = 2001, end = 2015)
ts.plot(ts_midwest.2)

ts_maritimes.2<-ts(data = cancer_maritimes.2,frequency = n_distinct(cancer_maritimes.2$GEO) , start = 2001, end = 2015)
ts.plot(ts_maritimes.2)

ts_territories.2<-ts(data = cancer_territories.2, frequency = n_distinct(cancer_territories.2$GEO) ,start = 2001, end = 2015)
ts.plot(ts_territories.2)

class(ts_BC.2)
####SO the frequency used is the number of distinct values in the GEO feature. 
####This is because this is the "interval" that repeats over time.
##"Argument frequency indicates the sampling frequency of the time series, with the default value 1 indicating one sample in each unit time interval."
```
```{r decomposition plots}
plot(decompose(ts_ON.2[,4]))
plot(decompose(ts_ON.2[,5]))
plot(decompose(ts_ON.2[,6]))
#plot(decompose(ts_ON.2[,7], na.action(na.pass)))
#plot(decompose(ts_ON.2[,8],na.action(na.pass)))

plot(decompose(ts_QC.2[,4]))
plot(decompose(ts_QC.2[,5]))
plot(decompose(ts_QC.2[,6]))

plot(decompose(ts_BC.2[,4]))
plot(decompose(ts_BC.2[,5]))
plot(decompose(ts_BC.2[,6]))

plot(decompose(ts_midwest.2[,4]))##residuals are not white noise
plot(decompose(ts_midwest.2[,5]))##residuals are not white noise
plot(decompose(ts_midwest.2[,6]))##residuals are not white noise

plot(decompose(ts_maritimes.2[,4]))
plot(decompose(ts_maritimes.2[,5]))##residuals are not white noise
plot(decompose(ts_maritimes.2[,6]))

plot(decompose(ts_territories.2[,4]))
plot(decompose(ts_territories.2[,5]))
plot(decompose(ts_territories.2[,6]))


```



```{r preliminary time series analysis.2}
##All cancer

ts.plot(ts_ON.2[,4], main = "All sites of cancer")
ts.plot(ts_QC.2[,4], main = "All sites of cancer")
ts.plot(ts_BC.2[,4], main = "All sites of cancer")
ts.plot(ts_midwest.2[,4], main = "All sites of cancer")
ts.plot(ts_maritimes.2[,4], main = "All sites of cancer")
ts.plot(ts_territories.2[,4], main = "All sites of cancer")

#Lung

ts.plot(ts_ON.2[,5], main="Bronchus and lung cancer")
ts.plot(ts_QC.2[,5], main="Bronchus and lung cancer")
ts.plot(ts_BC.2[,5], main="Bronchus and lung cancer")
ts.plot(ts_midwest.2[,5], main="Bronchus and lung cancer")
ts.plot(ts_maritimes.2[,5], main="Bronchus and lung cancer")
ts.plot(ts_territories.2[,5], main="Bronchus and lung cancer")


#Colon

ts.plot(ts_ON.2[,6], main="Colon cancer")
ts.plot(ts_QC.2[,6], main="Colon cancer")
ts.plot(ts_BC.2[,6], main="Colon cancer")
ts.plot(ts_midwest.2[,6], main="Colon cancer")
ts.plot(ts_maritimes.2[,6], main="Colon cancer")
ts.plot(ts_territories.2[,6], main="Colon cancer")


```


```{r preliminary time series analysis-2}
###check ACF to determine what predictive model to use
#Ontario
acf(ts_ON.2[,4], type = "correlation")
acf(ts_ON.2[,4], type= "partial")
acf(ts_ON.2[,5], type = "correlation")
acf(ts_ON.2[,5], type= "partial")
acf(ts_ON.2[,6], type = "correlation")
acf(ts_ON.2[,6], type= "partial")

#Quebec
acf(ts_QC.2[,4], type = "correlation")
acf(ts_QC.2[,4], type= "partial")
acf(ts_QC.2[,5], type = "correlation")
acf(ts_QC.2[,5], type= "partial")
acf(ts_QC.2[,6], type = "correlation")
acf(ts_QC.2[,6], type= "partial")

#BRITISH COLUMBIA
acf(ts_BC.2[,4], type = "correlation")
acf(ts_BC.2[,4], type= "partial")
acf(ts_BC.2[,5], type = "correlation")
acf(ts_BC.2[,5], type= "partial")
acf(ts_BC.2[,6], type = "correlation")
acf(ts_BC.2[,6], type= "partial")

##MIDWEST
acf(ts_midwest.2[,4], type = "correlation")
acf(ts_midwest.2[,4], type= "partial")
acf(ts_midwest.2[,5], type = "correlation")
acf(ts_midwest.2[,5], type= "partial")
acf(ts_midwest.2[,6], type = "correlation")
acf(ts_midwest.2[,6], type= "partial")

#Maritimes
acf(ts_maritimes.2[,4], type = "correlation")
acf(ts_maritimes.2[,4], type= "partial")
acf(ts_maritimes.2[,5], type = "correlation")
acf(ts_maritimes.2[,5], type= "partial")
acf(ts_maritimes.2[,6], type = "correlation")
acf(ts_maritimes.2[,6], type= "partial")

#territories
acf(ts_territories.2[,4], type = "correlation")
acf(ts_territories.2[,4], type= "partial")
acf(ts_territories.2[,5], type = "correlation")
acf(ts_territories.2[,5], type= "partial")
acf(ts_territories.2[,6], type = "correlation")
acf(ts_territories.2[,6], type= "partial")

#####
###doesn't look like any of them are sufficiently stationary
##makes me want to use ARIMA
##time series regression
###see decomposition
```


```{r preliminary time series analysis.stationarity}
##tests for stationarity
#ljung-box - non-stationary will have low p-value
##other tests indicated a lag of 6 so we will see how this changes the ljung-box test
Box.test(ts_ON.2[,4], type="Ljung-Box")
Box.test(ts_ON.2[,5], type="Ljung-Box")
Box.test(ts_ON.2[,6], type="Ljung-Box")

Box.test(ts_QC.2[,4], type="Ljung-Box")##fail to reject null of stationarity
Box.test(ts_QC.2[,5], type="Ljung-Box")
Box.test(ts_QC.2[,6], type="Ljung-Box")

Box.test(ts_BC.2[,4], type="Ljung-Box")
Box.test(ts_BC.2[,5], type="Ljung-Box")
Box.test(ts_BC.2[,6], type="Ljung-Box")

Box.test(ts_midwest.2[,4], type="Ljung-Box")
Box.test(ts_midwest.2[,5], type="Ljung-Box")
Box.test(ts_midwest.2[,6], type="Ljung-Box")##fail to reject null of stationarity

Box.test(ts_maritimes.2[,4], type="Ljung-Box")
Box.test(ts_maritimes.2[,5], type="Ljung-Box")
Box.test(ts_maritimes.2[,6], type="Ljung-Box")

Box.test(ts_territories.2[,4], type="Ljung-Box")##fail to reject null of stationarity
Box.test(ts_territories.2[,5], type="Ljung-Box")##fail to reject null of stationarity
Box.test(ts_territories.2[,6], type="Ljung-Box")##fail to reject null of stationarity
#generally reject the null that these are stationary time series

#stationary might indicate that there is an equally likely 
#chance of cancer diagnosis regardless of location
```


```{r preliminary time series analysis.stationarity.2}
#Augmented dickey-fuller t-stat test for unit root
options(warn = -1)
#non-stationary has a large p-value
adf.test(ts_ON.2[,4])
adf.test(ts_ON.2[,5])
adf.test(ts_ON.2[,6])

adf.test(ts_QC.2[,4])
adf.test(ts_QC.2[,5])
adf.test(ts_QC.2[,6])

adf.test(ts_BC.2[,4])
adf.test(ts_BC.2[,5])
adf.test(ts_BC.2[,6])

adf.test(ts_midwest.2[,4])
adf.test(ts_midwest.2[,5])
adf.test(ts_midwest.2[,6])

adf.test(ts_maritimes.2[,4])
adf.test(ts_maritimes.2[,5])
adf.test(ts_maritimes.2[,6])

adf.test(ts_territories.2[,4])##fail to reject null of non-stationarity
adf.test(ts_territories.2[,5])##fail to reject null of non-stationarity
adf.test(ts_territories.2[,6])##fail to reject null of non-stationarity
##reject the null of non-stationarity for all except ^^
```


```{r preliminary time series analysis.stationarity.3}
##KPSS for level or trend stationarity
options(warn = -1)
## lower p-value indicates non stationarity
kpss.test(ts_ON.2[,4], null = "Trend")
kpss.test(ts_ON.2[,5], null = "Trend")
kpss.test(ts_ON.2[,6], null = "Trend")

kpss.test(ts_QC.2[,4], null = "Trend")
kpss.test(ts_QC.2[,5], null = "Trend")
kpss.test(ts_QC.2[,6], null = "Trend")

kpss.test(ts_BC.2[,4], null = "Trend")
kpss.test(ts_BC.2[,5], null = "Trend")
kpss.test(ts_BC.2[,6], null = "Trend")

kpss.test(ts_midwest.2[,4], null = "Trend")##reject the null that this is level stationary
kpss.test(ts_midwest.2[,5], null = "Trend")##reject the null that this is level stationary
kpss.test(ts_midwest.2[,6], null = "Trend")##reject the null that this is level/trend stationary

kpss.test(ts_maritimes.2[,4], null = "Trend")##reject the null that this is level/trend stationary
kpss.test(ts_maritimes.2[,5], null = "Trend")##reject the null that this is trend stationary
kpss.test(ts_maritimes.2[,6], null = "Trend")##reject the null that this is level/trend stationary

kpss.test(ts_territories.2[,4], null = "Trend")
kpss.test(ts_territories.2[,5], null = "Trend")
kpss.test(ts_territories.2[,6], null = "Trend")

##cannot reject the null of stationarity, p-value indicates they could be stationary 

```

```{r train/test split for time series}
split.ON<-ts_split(ts.obj=ts_ON.2, sample.out =104)
train.ON<- split.ON$train
test.ON<- split.ON$test

split.QC<- ts_split(ts_QC.2, sample.out = 38)
train.QC<- split.QC$train
test.QC<- split.QC$test

split.BC<- ts_split(ts_BC.2, sample.out = 34)
train.BC<- split.BC$train
test.BC<- split.BC$test

split.mid<- ts_split(ts_midwest.2, sample.out =48)
train.mid<- split.mid$train
test.mid<- split.mid$test

split.mar<- ts_split(ts_maritimes.2, sample.out = 38)
train.mar<- split.mar$train
test.mar<- split.mar$test

split.terr<- ts_split(ts_territories.2, sample.out = 6)
train.terr<-split.terr$train
test.terr<-split.terr$test

```



```{r time series model}
#TSLM
#need to train models
##time series regression [tsr]-> tslm

tsr_ON<- tslm(formula= train.ON[,4]~GEO+Sex,data=train.ON)
summary(tsr_ON)
tsr_ON.5<- tslm(formula= train.ON[,5]~GEO+Sex,data=train.ON)
summary(tsr_ON.5)
tsr_ON.6<- tslm(formula= train.ON[,6]~GEO+Sex,data=train.ON)
summary(tsr_ON.6)
##tsr_ON.7 <- tslm(formula= train.ON[,7]~GEO, data=train.ON)
##summary(tsr_ON.7)
##tsr_ON.8<- tslm(formula= train.ON[,8]~GEO, data=train.ON)
##summary(tsr_ON.8)

tsr_QC<- tslm(formula = train.QC[,4]~GEO+Sex, data = train.QC)
summary(tsr_QC)
tsr_QC.5<- tslm(formula= train.QC[,5]~GEO+Sex, data=train.QC)
summary(tsr_QC.5)
tsr_QC.6<- tslm(formula= train.QC[,6]~GEO+Sex, data=train.QC)
summary(tsr_QC.6)
##tsr_QC.7<- tslm(formula= train.QC[,7]~GEO, data=train.QC)
##summary(tsr_QC.7)
#tsr_QC.8<- tslm(formula= train.QC[,8]~GEO, data=train.QC)
#summary(tsr_QC.8)

tsr_BC<- tslm(formula = train.BC[,4]~GEO+Sex, data = train.BC)
summary(tsr_BC)
tsr_BC.5<- tslm(formula = train.BC[,5]~GEO+Sex, data = train.BC)
summary(tsr_BC.5)
tsr_BC.6<-tslm(formula = train.BC[,6]~GEO+Sex, data=train.BC)
summary(tsr_BC.6)

tsr_mid<-tslm(formula = train.mid[,4]~GEO+Sex, data=train.mid)
summary(tsr_mid)
tsr_mid.5<-tslm(formula = train.mid[,5]~GEO+Sex, data=train.mid)
summary(tsr_mid.5)
tsr_mid.6<- tslm(formula = train.mid[,6]~GEO+Sex, data=train.mid)
summary(tsr_mid.6)

tsr_mar<-tslm(formula = train.mar[,4]~GEO+Sex, data= train.mar)
summary(tsr_mar)
tsr_mar.5<- tslm(formula = train.mar[,5]~GEO+Sex, data = train.mar)
summary(tsr_mar.5)
tsr_mar.6<- tslm(formula = train.mar[,6]~GEO+Sex, data = train.mar)
summary(tsr_mar.6)

tsr_terr<- tslm(formula = train.terr[,4]~GEO+Sex, data = train.terr)
summary(tsr_terr)
tsr_terr.5<- tslm(formula = train.terr[,5]~GEO+Sex, data = train.terr)
summary(tsr_terr.5)
tsr_terr.6<-tslm(formula = train.terr[,6]~GEO+Sex, data = train.terr)


```


```{r predictions ONTARIO}
##test predictions

newdata.1<- data.frame(
  ï..REF_DATE = test.ON[,1],
  GEO = test.ON[,2],
  Sex = test.ON[,3]
)
fcast.ON.4<-forecast(tsr_ON, newdata = newdata.1,h=2)
autoplot(fcast.ON.4)+
  autolayer(test.ON[,4])

newdata.2<- data.frame(
  GEO = test.ON[,2],
  Sex = test.ON[,3]
)
fcast.ON.5<-forecast(tsr_ON.5, newdata = newdata.2,h=2)
autoplot(fcast.ON.5)+
  autolayer(test.ON[,5])

newdata.3<- data.frame(
  GEO = test.ON[,2],
  Sex = test.ON[,3]
)
fcast.ON.6<-forecast(tsr_ON.6, newdata = newdata.3,h=2)
autoplot(fcast.ON.6, h=2)+
  autolayer(test.ON[,6])

```

```{r predictions QUEBEC}

newdata.1.1<- data.frame(
  GEO = test.QC[,2],
  Sex = test.QC[,3]
)
fcast.QC.4<-forecast(tsr_QC, newdata = newdata.1.1,h=2)
autoplot(fcast.QC.4)+
  autolayer(test.QC[,4])

newdata.2.1<- data.frame(
  GEO = test.QC[,2],
  Sex = test.QC[,3]
)
fcast.QC.5<-forecast(tsr_QC.5, newdata = newdata.2.1,h=2)
autoplot(fcast.QC.5)+
  autolayer(test.QC[,5])

newdata.3.1<- data.frame(
  GEO = test.QC[,2],
  Sex = test.QC[,3]
)
fcast.QC.6<-forecast(tsr_QC.6, newdata = newdata.3.1,h=2)
autoplot(fcast.QC.6)+
  autolayer(test.QC[,6])


```

```{r predictions BC}
newdata.1.2<- data.frame(
  GEO = test.BC[,2],
  Sex = test.BC[,3]
)
fcast.BC.4<-forecast(tsr_BC, newdata = newdata.1.2,h=2)
autoplot(fcast.BC.4)+
  autolayer(test.BC[,4])

newdata.2.2<- data.frame(
  GEO = test.BC[,2],
  Sex = test.BC[,3]
)
fcast.BC.5<-forecast(tsr_BC.5, newdata = newdata.2.2,h=2)
autoplot(fcast.BC.5)+
  autolayer(test.BC[,5])

newdata.3.2<- data.frame(
  GEO = test.BC[,2],
  Sex = test.BC[,3]
)
fcast.BC.6<-forecast(tsr_BC.6, newdata = newdata.3.2,h=2)
autoplot(fcast.BC.6)+
  autolayer(test.BC[,6])

```

```{r PREDICTIONS MIDWEST}

newdata.1.3<- data.frame(
  GEO = test.mid[,2],
  Sex = test.mid[,3]
)
fcast.mid.4<-forecast(tsr_mid, newdata = newdata.1.3,h=2)
autoplot(fcast.mid.4)+
  autolayer(test.mid[,4])

newdata.2.3<- data.frame(
  GEO = test.mid[,2],
  Sex = test.mid[,3]
)
fcast.mid.5<-forecast(tsr_mid.5, newdata = newdata.2.3,h=2)
autoplot(fcast.mid.5)+
  autolayer(test.mid[,5])

newdata.3.3<- data.frame(
  GEO = test.mid[,2],
  Sex = test.mid[,3]
)
fcast.mid.6<-forecast(tsr_mid.6, newdata = newdata.3.3,h=2)
autoplot(fcast.mid.6)+
  autolayer(test.mid[,6])

```

```{r predictions maritimes}
newdata.1.4<- data.frame(
  GEO = test.mar[,2],
  Sex = test.mar[,3]
)
fcast.mar.4<-forecast(tsr_mar, newdata = newdata.1.4,h=2)
autoplot(fcast.mar.4)+
  autolayer(test.mar[,4])

newdata.2.4<- data.frame(
  GEO = test.mar[,2],
  Sex = test.mar[,3]
)
fcast.mar.5<-forecast(tsr_mar.5, newdata = newdata.2.4,h=2)
autoplot(fcast.mar.5)+
  autolayer(test.mar[,5])

newdata.3.4<- data.frame(
  GEO = test.mar[,2],
  Sex = test.mar[,3]
)
fcast.mar.6<-forecast(tsr_mar.6, newdata = newdata.3.4,h=2)
autoplot(fcast.mar.6)+
  autolayer(test.mar[,6])

```

```{r predictions Territories}
newdata.1.5<- data.frame(
  GEO = test.terr[,2],
  Sex = test.terr[,3]
)
fcast.terr.4<-forecast(tsr_terr, newdata = newdata.1.5,h=2)
autoplot(fcast.terr.4)+
  autolayer(test.terr[,4])

newdata.2.5<- data.frame(
  GEO = test.terr[,2],
  Sex = test.terr[,3]
)
fcast.terr.5<-forecast(tsr_terr.5, newdata = newdata.2.5,h=2)
autoplot(fcast.terr.5)+
  autolayer(test.terr[,5])

newdata.3.5<- data.frame(
  GEO = test.terr[,2],
  Sex = test.terr[,3]
)
fcast.terr.6<-forecast(tsr_terr.6, newdata = newdata.3.5,h=2)
autoplot(fcast.terr.6)+
  autolayer(test.terr[,6])

```


```{r ARIMA Ontario}
##ARIMA model or SARIMA
##trying non seasonal ARIMA models
##with the currently non differenced data

##staring with auto.arima
####################All cancer sites
#(auto.arima(train.ON[,4], seasonal = TRUE))
#(Arima(train.ON[,4], order = c(1,0,5), seasonal = c(1,0,1)))#model from auto.arima
#AIC=6659.09   AICc=6659.45   BIC=6703.47

#(Arima(train.ON[,4], order = c(1,1,6), seasonal = c(0,1,1)))
#(arima_ON.m<- Arima(train.ON[,4], order = c(1,1,6), seasonal = c(1,1,1)))
#AIC=6127.88   AICc=6128.27   BIC=6171.37

#(arima_ON.m<- Arima(train.ON[,4], order = c(1,1,8), seasonal = c(0,1,1)))
#AIC=6089.67   AICc=6090.14   BIC=6137.51

arima_ON.m<- Arima(train.ON[,4], order = c(1,1,8), seasonal = c(0,1,2))####BEST AIC
#AIC=5865.88   AICc=5866.44   BIC=5918.07

#################Lungs
#(arima_ON.5<- auto.arima(train.ON[,5], seasonal = TRUE))
#(arima_ON.5<- Arima(train.ON[,5], order = c(1,0,5), seasonal = c(0,0,1)))#model from auto.arima
#AIC=5183.45   AICc=5183.75   BIC=5223.39

#(arima_ON.5.m<- Arima(train.ON[,5], order = c(1,0,5), seasonal = c(0,1,1)))
# AIC=4791.34   AICc=4791.6   BIC=4826.15

#(arima_ON.5.m<- Arima(train.ON[,5], order = c(1,0,7), seasonal = c(0,1,1))) 
#AIC=4742.87   AICc=4743.26   BIC=4786.38

#(arima_ON.5.m<- Arima(train.ON[,5], order = c(1,0,8), seasonal = c(0,1,2)))
#AIC=4506.99   AICc=4507.55   BIC=4559.2

arima_ON.5.m<- Arima(train.ON[,5], order = c(1,0,9), seasonal = c(0,1,2))##BEST AIC
#AIC=4497.12   AICc=4497.77   BIC=4553.68

#############################COLON
#(arima_ON.6<- auto.arima(train.ON[,6], seasonal = FALSE)) #False higher AIC than True
#(arima_ON.6.m<- Arima(train.ON[,6], order = c(1,0,5), seasonal = c(0,0,0)))#model from auto.arima
#AIC=4753.36   AICc=4753.59   BIC=4788.86

#(arima_ON.6.m<- Arima(train.ON[,6], order = c(1,0,6), seasonal = c(0,0,0)))
#AIC=4689.1   AICc=4689.39   BIC=4729.04

#(arima_ON.6.m<- Arima(train.ON[,6], order = c(1,0,5), seasonal = c(0,1,1)))
#AIC=4437.09   AICc=4437.35   BIC=4471.9

#(arima_ON.6.m<- Arima(train.ON[,6], order = c(1,0,6), seasonal = c(0,1,1)))
#AIC=4352.96   AICc=4353.28   BIC=4392.12

#(arima_ON.6.m<- Arima(train.ON[,6], order = c(1,0,7), seasonal = c(0,1,1)))
#AIC=4335.71   AICc=4336.1   BIC=4379.22

arima_ON.6.m<- Arima(train.ON[,6], order = c(1,0,8), seasonal = c(0,1,2))##BEST AIC
#AIC=4117.67   AICc=4118.23   BIC=4169.88
```

```{r ARIMA predict/forecast ONTARIO}

fcast_ON.4<-forecast(arima_ON.m)
autoplot(fcast_ON.4)+
  autolayer(test.ON[,4])

fcast_ON.5<-forecast(arima_ON.5.m)
autoplot(fcast_ON.5)+
  autolayer(test.ON[,5])

fcast_ON.6<-forecast(arima_ON.6.m)
autoplot(fcast_ON.6)+
  autolayer(test.ON[,6])

```

```{r ARIMA QC}
#######################All cancer sites
#(arima_QC<- auto.arima(train.QC[,4], seasonal = TRUE))
#(arima_QC<- Arima(train.QC[,4], order = c(1,0,1), seasonal = c(0,0,1)))##auto.arima model
#AIC=2813.12   AICc=2813.38   BIC=2830.28

#(arima_QC.m<- Arima(train.QC[,4], order = c(1,0,3), seasonal = c(0,0,1)))
#AIC=2799.16   AICc=2799.66   BIC=2823.19

#(arima_QC.m<- Arima(train.QC[,4], order = c(1,0,3), seasonal = c(0,1,1)))
#AIC=2570.48   AICc=2570.89   BIC=2590.56

#(arima_QC.m<- Arima(train.QC[,4], order = c(1,1,4), seasonal = c(0,1,1)))
#AIC=2568.64   AICc=2569.2   BIC=2592.04

arima_QC.m<- Arima(train.QC[,4], order = c(1,1,4), seasonal = c(0,1,2))##BEST AIC
#AIC=2526.05   AICc=2526.77   BIC=2552.79

##########################LUNGS
#(arima_QC.5<- auto.arima(train.QC[,5], seasonal = TRUE))
#(arima_QC.5<-Arima(train.QC[,5], order = c(0,0,1), seasonal = c(0,0,2)))##auto.arima model
#AIC=2407.76   AICc=2408.02   BIC=2424.92

#(arima_QC.5.m<-Arima(train.QC[,5], order = c(1,0,4), seasonal = c(0,1,2)))
#AIC=2190.36   AICc=2191.08   BIC=2217.14

#(arima_QC.5.m<-Arima(train.QC[,5], order = c(1,1,4), seasonal = c(0,1,2)))
#AIC=2188.35   AICc=2189.07   BIC=2215.09

#(arima_QC.5.m<-Arima(train.QC[,5], order = c(1,1,4), seasonal = c(0,1,3)))
#AIC=2178.95   AICc=2179.85   BIC=2209.03

#(arima_QC.5.m<-Arima(train.QC[,5], order = c(1,1,4), seasonal = c(0,1,4)))
#AIC=2125.93   AICc=2127.04   BIC=2159.36
arima_QC.5.m<-Arima(train.QC[,5], order = c(1,1,4), seasonal = c(0,1,5))
#AIC=2104.38   AICc=2105.72   BIC=2141.14

############################# Colon
#(arima_QC.6<- auto.arima(train.QC[,6], seasonal = TRUE))
#(arima_QC.6.m<-Arima(train.QC[,6], order = c(0,0,3), seasonal = c(0,0,1)))##auto.arima model
#AIC=2258.1   AICc=2258.48   BIC=2278.7

#(arima_QC.6.m<-Arima(train.QC[,6], order = c(4,0,3), seasonal = c(0,0,1)))
#AIC=2250.51   AICc=2251.52   BIC=2284.85

#(arima_QC.6.m<-Arima(train.QC[,6], order = c(1,0,3), seasonal = c(0,1,1)))
#AIC=2114.69   AICc=2115.11   BIC=2134.78

#(arima_QC.6.m<-Arima(train.QC[,6], order = c(1,0,3), seasonal = c(0,2,1)))
#AIC=2110.41   AICc=2110.86   BIC=2129.92

#(arima_QC.6.m<-Arima(train.QC[,6], order = c(1,0,3), seasonal = c(0,2,4)))
#AIC=2005.74   AICc=2006.74   BIC=2035.01

arima_QC.6.m<-Arima(train.QC[,6], order = c(1,0,3), seasonal = c(0,2,5))##BEST AIC
#AIC=1980.22   AICc=1981.44   BIC=2012.74


```

```{r ARIMA predict/forecast Quebec}

fcast_QC.4<-forecast(arima_QC.m)
autoplot(fcast_QC.4)+
  autolayer(test.QC[,4])

fcast_QC.5<-forecast(arima_QC.5.m)
autoplot(fcast_QC.5)+
  autolayer(test.QC[,5])

fcast_QC.6<-forecast(arima_QC.6.m)
autoplot(fcast_QC.6)+
  autolayer(test.QC[,6])

```

```{r ARIMA BC}
##############################ALL cancer sites
#(arima_BC<-auto.arima(train.BC[,4], seasonal = TRUE))
#(arima_BC<- Arima(train.BC[,4], order = c(1,0,5), seasonal = c(0,0,1)))#auto.arima model
#AIC=2187.68   AICc=2188.6   BIC=2217.58

#(arima_BC.m<- Arima(train.BC[,4], order = c(1,0,5), seasonal = c(0,1,1)))
#AIC=2041.8   AICc=2042.6   BIC=2067.69

#(arima_BC.m<- Arima(train.BC[,4], order = c(1,0,6), seasonal = c(0,1,1)))
#AIC=2020.01   AICc=2021.02   BIC=2049.14

#(arima_BC.m<- Arima(train.BC[,4], order = c(1,0,9), seasonal = c(0,1,2)))
#AIC=1917.45   AICc=1919.54   BIC=1959.52

#(arima_BC.m<- Arima(train.BC[,4], order = c(1,0,9), seasonal = c(0,1,3)))
#AIC=1906.1   AICc=1908.53   BIC=1951.41

#(arima_BC.m<- Arima(train.BC[,4], order = c(1,0,9), seasonal = c(0,1,4)))
#AIC=1847.06   AICc=1849.85   BIC=1895.61

#(arima_BC.m<- Arima(train.BC[,4], order = c(1,0,9), seasonal = c(0,1,5)))
#AIC=1823.34   AICc=1826.52   BIC=1875.12

#(arima_BC.m<- Arima(train.BC[,4], order = c(1,0,9), seasonal = c(0,1,6)))
#AIC=1815.42   AICc=1819.02   BIC=1870.44

#(arima_BC.m<- Arima(train.BC[,4], order = c(1,0,9), seasonal = c(0,1,7)))
#AIC=1784.21   AICc=1788.26   BIC=1842.46

arima_BC.m<- Arima(train.BC[,4], order = c(1,0,9), seasonal = c(0,1,8))
#AIC=1779.17   AICc=1783.69   BIC=1840.66
##takes forever to run

#############################################LUNGS
#(arima_BC.5<-auto.arima(train.BC[,5], seasonal = FALSE))##better than seasonal=TRUE
#AIC=1531.24   AICc=1531.98   BIC=1557.82

#(arima_BC.5.m<- Arima(train.BC[,5], order = c(2,0,4), seasonal = c(0,1,1)))
#AIC=1358.72   AICc=1359.53   BIC=1384.62

#(arima_BC.5.m<- Arima(train.BC[,5], order = c(2,0,4), seasonal = c(1,1,1)))
#AIC=1334.85   AICc=1335.86   BIC=1363.98

#(arima_BC.5.m<- Arima(train.BC[,5], order = c(2,0,4), seasonal = c(1,1,4)))
#AIC=1242.85   AICc=1244.64   BIC=1281.69

arima_BC.5.m<- Arima(train.BC[,5], order = c(2,0,4), seasonal = c(2,1,4))###BEST AIC
#AIC=1148.16   AICc=1150.25   BIC=1190.23

################################# Colon
#(arima_BC.6<-auto.arima(train.BC[,6], seasonal = TRUE))
#(arima_BC.6.m<- Arima(train.BC[,6], order = c(1,0,5), seasonal = c(0,0,2)))#auto.arima model
#AIC=1444.7   AICc=1445.83   BIC=1477.93

#(arima_BC.6.m<- Arima(train.BC[,6], order = c(1,0,5), seasonal = c(0,1,2)))
#AIC=1361.42   AICc=1362.43   BIC=1390.55

#(arima_BC.6.m<- Arima(train.BC[,6], order = c(1,0,5), seasonal = c(0,1,4)))
#AIC=1302.51   AICc=1304.01   BIC=1338.11

arima_BC.6.m<- Arima(train.BC[,6], order = c(1,0,5), seasonal = c(0,1,5))##BEST AIC
#AIC=1295.83   AICc=1297.62   BIC=1334.67

```

```{r ARIMA predict/forecast BC}

fcast_BC.4<-forecast(arima_BC.m)
autoplot(fcast_BC.4)+
  autolayer(test.BC[,4])

fcast_BC.5<-forecast(arima_BC.5.m)
autoplot(fcast_BC.5)+
  autolayer(test.BC[,5])

fcast_BC.6<-forecast(arima_BC.6.m)
autoplot(fcast_BC.6)+
  autolayer(test.BC[,6])

```


```{r ARIMA midwest}
##################################ALL cancer sites
#(arima_mid<- auto.arima(train.mid[,4], seasonal= TRUE))
#(arima_mid.m<- Arima(train.mid[,4], order = c(2,0,2), seasonal = c(1,1,0)))#auto.arima model
#AIC=2581.3   AICc=2581.62   BIC=2602.77

#(arima_mid.m<- Arima(train.mid[,4], order = c(2,0,3), seasonal = c(1,1,0)))
#AIC=2577.45   AICc=2577.88   BIC=2602.51

#(arima_mid.m<- Arima(train.mid[,4], order = c(2,0,3), seasonal = c(1,1,1)))
#AIC=2555.31   AICc=2555.87   BIC=2583.95

#(arima_mid.m<- Arima(train.mid[,4], order = c(2,0,3), seasonal = c(1,2,1)))
#AIC=2442.21   AICc=2442.83   BIC=2470.09

#(arima_mid.m<- Arima(train.mid[,4], order = c(2,0,3), seasonal = c(1,2,3)))
#AIC=2419.11   AICc=2420.07   BIC=2453.96

#(arima_mid.m<- Arima(train.mid[,4], order = c(2,0,3), seasonal = c(1,2,5)))
#AIC=2412.21   AICc=2413.58   BIC=2454.02

arima_mid.m<- Arima(train.mid[,4], order = c(2,0,3), seasonal = c(1,2,6))##no noticeable improvement from 6->8 
#AIC=2405.48   AICc=2407.08   BIC=2450.78

###########################################LUNGS
#(arima_mid.5<- auto.arima(train.mid[,5], seasonal= TRUE))
#(arima_mid.5.m<- Arima(train.mid[,5], order = c(5,1,2), seasonal = c(2,0,1)))##auto.arima model
#AIC=2239.1   AICc=2240.24   BIC=2283.06

#(arima_mid.5.m<- Arima(train.mid[,5], order = c(5,1,3), seasonal = c(2,0,1)))
#AIC=2169.99   AICc=2171.12   BIC=2213.94

#(arima_mid.5.m<- Arima(train.mid[,5], order = c(5,1,3), seasonal = c(2,1,1)))
#AIC=2022.71   AICc=2023.95   BIC=2065.62

#(arima_mid.5.m<- Arima(train.mid[,5], order = c(5,1,3), seasonal = c(2,1,2)))
#AIC=2020.75   AICc=2022.2   BIC=2067.23

#(arima_mid.5.m<- Arima(train.mid[,5], order = c(5,1,3), seasonal = c(2,2,2)))
#AIC=2000.26   AICc=2001.87   BIC=2045.51

#(arima_mid.5.m<- Arima(train.mid[,5], order = c(5,2,3), seasonal = c(2,2,2)))
#AIC=1991.14   AICc=1992.75   BIC=2036.33 ##also solved warning in previous version 

arima_mid.5.m<- Arima(train.mid[,5], order = c(5,2,4), seasonal = c(2,2,2))##BEST AIC
#AIC=1971.84   AICc=1973.72   BIC=2020.52

########################################## Colon
#(arima_mid.6<- auto.arima(train.mid[,6], seasonal= TRUE))
#(arima_mid.5.m<- Arima(train.mid[,6], order = c(2,0,0), seasonal = c(2,1,1))) ##auto.arima model
#AIC=1904.11   AICc=1904.55   BIC=1929.17

#(arima_mid.5.m<- Arima(train.mid[,6], order = c(2,0,2), seasonal = c(2,1,1)))
#AIC=1898.68   AICc=1899.24   BIC=1927.32

#(arima_mid.5.m<- Arima(train.mid[,6], order = c(2,1,2), seasonal = c(2,1,1)))
#AIC=1891.71   AICc=1892.28   BIC=1920.32

#(arima_mid.5.m<- Arima(train.mid[,6], order = c(2,1,2), seasonal = c(2,1,2)))
#AIC=1887.73   AICc=1888.44   BIC=1919.92

#(arima_mid.5.m<- Arima(train.mid[,6], order = c(2,1,2), seasonal = c(2,2,2)))
#AIC=1851.87   AICc=1852.65   BIC=1883.19

arima_mid.6.m<- Arima(train.mid[,6], order = c(2,1,2), seasonal = c(2,3,2)) ##BEST AIC
#AIC=1840.36   AICc=1841.23   BIC=1870.74

```

```{r ARIMA predict/forecast midwest}

fcast_mid.4<-forecast(arima_mid.m)
autoplot(fcast_mid.4)+
  autolayer(test.mid[,4])

fcast_mid.5<-forecast(arima_mid.5.m)
autoplot(fcast_mid.5)+
  autolayer(test.mid[,5])

fcast_mid.6<-forecast(arima_mid.6.m)
autoplot(fcast_mid.6) +
  autolayer(test.mid[,6])

```

```{r ARIMA maritimes}
#(arima_mar<- auto.arima(train.mar[,4], seasonal = TRUE))
#(arima_mar.m <- Arima(train.mar[,4], order = c(4,1,0) ,seasonal = c(0,0,2))) #auto.arima model
#AIC=2201.95   AICc=2202.61   BIC=2229.38

#(arima_mar.m <- Arima(train.mar[,4], order = c(4,1,1) ,seasonal = c(0,0,2)))
#AIC=2198.94   AICc=2199.6   BIC=2226.37

#(arima_mar.m <- Arima(train.mar[,4], order = c(4,1,3) ,seasonal = c(0,0,2)))
#AIC=2131.73   AICc=2132.74   BIC=2166.02

#(arima_mar.m <- Arima(train.mar[,4], order = c(4,1,3) ,seasonal = c(0,1,2)))
#AIC=2002.72   AICc=2003.83   BIC=2036.14

#(arima_mar.m <- Arima(train.mar[,4], order = c(4,1,3) ,seasonal = c(0,2,2)))
#AIC=1916.7   AICc=1917.93   BIC=1949.17

arima_mar.m <- Arima(train.mar[,4], order = c(4,1,3) ,seasonal = c(0,2,3))## BEST AIC
#AIC=1915.16   AICc=1916.65   BIC=1950.88

######################################LUNGS
#(arima_mar.5<- auto.arima(train.mar[,5], seasonal = TRUE))
#(arima_mar.5.m<- Arima(train.mar[,5], order = c(5,0,1), seasonal = c(0,0,2)))##auto.arima model
#AIC=1663.09   AICc=1664.1   BIC=1697.42

#(arima_mar.5.m<- Arima(train.mar[,5], order = c(5,0,1), seasonal = c(0,1,2)))
#AIC=1581.21   AICc=1582.11   BIC=1611.33

#(arima_mar.5.m<- Arima(train.mar[,5], order = c(5,0,2), seasonal = c(0,1,2)))
#AIC=1558.89   AICc=1559.99   BIC=1592.36

#(arima_mar.5.m<- Arima(train.mar[,5], order = c(5,0,2), seasonal = c(0,2,2)))
#AIC=1516.86   AICc=1518.08   BIC=1549.38

#(arima_mar.5.m<- Arima(train.mar[,5], order = c(5,0,2), seasonal = c(0,3,2)))
#AIC=1474.06   AICc=1475.43   BIC=1505.54

arima_mar.5.m<- Arima(train.mar[,5], order = c(5,0,3), seasonal = c(0,3,2))##BEST AIC
#AIC=1472.04   AICc=1473.69   BIC=1506.66

############################### Colon
#(arima_mar.6<- auto.arima(train.mar[,6], seasonal = TRUE))
#(arima_mar.6.m<- Arima(train.mar[,6], order = c(0,1,5), seasonal = c(0,0,1))) #auto.arima model
#AIC=1668.67   AICc=1669.33   BIC=1696.1

#(arima_mar.6.m<- Arima(train.mar[,6], order = c(0,1,5), seasonal = c(0,1,1)))
#AIC=1596.2   AICc=1596.75   BIC=1619.59

#(arima_mar.6.m<- Arima(train.mar[,6], order = c(0,1,6), seasonal = c(0,1,1)))
#AIC=1566.62   AICc=1567.34   BIC=1593.36

#(arima_mar.6.m<- Arima(train.mar[,6], order = c(0,1,10), seasonal = c(0,1,4)))
#AIC=1497.4   AICc=1499.89   BIC=1547.53

#(arima_mar.6.m<- Arima(train.mar[,6], order = c(0,1,10), seasonal = c(0,1,5)))
#AIC=1491.06   AICc=1493.89   BIC=1544.54

#(arima_mar.6.m<- Arima(train.mar[,6], order = c(0,1,10), seasonal = c(0,2,5)))
#AIC=1471.18   AICc=1474.32   BIC=1523.13

#(arima_mar.6.m<- Arima(train.mar[,6], order = c(0,1,10), seasonal = c(0,3,5)))
#AIC=1469.12   AICc=1472.65   BIC=1519.38

arima_mar.6.m<- Arima(train.mar[,6], order = c(0,1,10), seasonal = c(0,3,6))##BEST AIC
#AIC=1462.55   AICc=1466.55   BIC=1515.95

```

```{r ARIMA predict/forecast Maritimes}

fcast_mar.4<-forecast(arima_mar.m)
autoplot(fcast_mar.4) +
  autolayer(test.mar[,4])

fcast_mar.5<-forecast(arima_mar.5.m)
autoplot(fcast_mar.5) +
  autolayer(test.mar[,5])

fcast_mar.6<-forecast(arima_mar.6.m)
autoplot(fcast_mar.6) +
  autolayer(test.mar[,6])

```

```{r ARIMA Territories}
#####################ALL cancer sites
#(arima_terr<-auto.arima(train.terr[,4], seasonal = TRUE, stepwise = FALSE, approximation = FALSE))
arima_terr.m<- Arima(train.terr[,4], order = c(0,0,0), seasonal = c(0,1,0))##auto.arima model
#AIC=347.42   AICc=347.55   BIC=348.95
##BEST AIC

############################### LUNGS
#(arima_terr.5<-auto.arima(train.terr[,5], seasonal = TRUE))
arima_terr.5.m<- Arima(train.terr[,5], order= c(0,0,0), seasonal = c(2,0,0))##auto.arima model
#AIC=283.85   AICc=285.1   BIC=290.29
##BEST AIC

################################# COlon
#(arima_terr.6<-auto.arima(train.terr[,6], seasonal = TRUE))
#>  ARIMA(2,1,0) 
#>  AIC=346.54   AICc=347.29   BIC=351.29
#(arima_terr.6.m<- Arima(train.terr[,5], order= c(2,1,1), seasonal = c(0,0,0)))
#AIC=287.9   AICc=289.19   BIC=294.24

#(arima_terr.6.m<- Arima(train.terr[,5], order= c(2,1,1), seasonal = c(0,1,0)))
#AIC=266.43   AICc=267.86   BIC=272.42

arima_terr.6.m<- Arima(train.terr[,5], order= c(2,1,1), seasonal = c(0,2,0))##BEST AIC
#AIC=258.47   AICc=260.07   BIC=264.07
```


```{r ARIMA predict/forecast territories}

fcast_terr.4<-forecast(arima_terr.m)
autoplot(fcast_terr.4) +
  autolayer(test.terr[,4])

fcast_terr.5<-forecast(arima_terr.5.m)
autoplot(fcast_terr.5) +
  autolayer(test.terr[,5])


fcast_terr.6<-forecast(arima_terr.6.m)
autoplot(fcast_terr.6) +
  autolayer(test.terr[,6])

```
```{r Time Series cross validation - Ontario}
##forecast function
f.ON<- function(y, h){forecast(arima_ON.m, h=h)}
##explore Exogenous predictor variables with xreg
#compare RMSE
on.1<-tsCV(ts_ON.2[,4], f.ON, h=2)
sqrt(mean(on.1^2, na.rm= TRUE))
##[1] 84.76661
sqrt(mean(residuals(f.ON(ts_ON.2, h=2))^2, na.rm=TRUE))
####[1] 30.27293

######lungs forcast
f.ON.5<-function(y, h){forecast(arima_ON.5.m, h=h)}
on.2<-tsCV(ts_ON.2[,5], f.ON.5, h=2)
sqrt(mean(on.2^2, na.rm= TRUE))
##[1] 19.05896
sqrt(mean(residuals(f.ON.5(ts_ON.2[,5], h=2))^2, na.rm=TRUE))
#[1] 9.144005
#####colon
f.ON.6<-function(y, h){forecast(arima_ON.6.m, h=h)}
on.3<-tsCV(ts_ON.2[,6], f.ON.6, h=2)
sqrt(mean(on.3^2, na.rm= TRUE))
##[1] 15.02973
sqrt(mean(residuals(f.ON.6(ts_ON.2[,6], h=2))^2, na.rm=TRUE))
###[1] 6.616241
```


```{r Accuracy Ontario}
#####################ARIMA

accuracy(fcast_ON.4, test.ON[,4])

accuracy(fcast_ON.5, test.ON[,5])

accuracy(fcast_ON.6, test.ON[,6])


################TSLM
accuracy(fcast.ON.4, test.ON[,4])

accuracy(fcast.ON.5, test.ON[,5])

accuracy(fcast.ON.6, test.ON[,6])
```
NOTE: MASE all are <1

```{r Accuracy Quebec}
#####################ARIMA
accuracy(fcast_QC.4, test.QC[,4])

accuracy(fcast_QC.5, test.QC[,5])

accuracy(fcast_QC.6, test.QC[,6])


################TSLM
accuracy(fcast.QC.4, test.QC[,4])

accuracy(fcast.QC.5, test.QC[,5])

accuracy(fcast.QC.6, test.QC[,6])
```

```{r Accuracy BC}
#####################ARIMA
accuracy(fcast_BC.4, test.BC[,4])

accuracy(fcast_BC.5, test.BC[,5])

accuracy(fcast_BC.6, test.BC[,6])


################TSLM
accuracy(fcast.BC.4, test.BC[,4])

accuracy(fcast.BC.5, test.BC[,5])

accuracy(fcast.BC.6, test.BC[,6])
```

```{r Accuracy Midwest}
#####################ARIMA
accuracy(fcast_mid.4, test.mid[,4])

accuracy(fcast_mid.5, test.mid[,5])

accuracy(fcast_mid.6, test.mid[,6])


################TSLM
accuracy(fcast.mid.4, test.mid[,4])

accuracy(fcast.mid.5, test.mid[,5])

accuracy(fcast.mid.6, test.mid[,6])
```

```{r Accuracy Maritimes}
#####################ARIMA
accuracy(fcast_mar.4, test.mar[,4])

accuracy(fcast_mar.5, test.mar[,5])

accuracy(fcast_mar.6, test.mar[,6])


################TSLM
accuracy(fcast.mar.4, test.mar[,4])

accuracy(fcast.mar.5, test.mar[,5])

accuracy(fcast.mar.6, test.mar[,6])
```

```{r Accuracy Territories}
#####################ARIMA
accuracy(fcast_terr.4, test.terr[,4])

accuracy(fcast_terr.5, test.terr[,5])

accuracy(fcast_terr.6, test.terr[,6])


################TSLM
accuracy(fcast.terr.4, test.terr[,4])

accuracy(fcast.terr.5, test.terr[,5])

accuracy(fcast.terr.6, test.terr[,6])
```